### ISSUE TITLE
Searching for necessary and purposeful APIs

### ISSUE THREAD

**Issue by 4teko7** [bounswe/2021SpringGroup1#48] opened 2021-05-27 12:19 UTC

**Comment by MrLebowski42** [comment] 2021-05-30 20:32
This was posted on our discord channel but you can find some public APIs from [here.](https://github.com/public-apis/public-apis)

**Comment by emiroztoprak** [comment] 2021-06-07 12:49
I found [Detect Language API](https://detectlanguage.com/), which can be used to find the languages in the title, description and text field of a post. It can also detect multiple languages in the given text.

**Comment by yunus-topal** [comment] 2021-06-07 13:11
I found <a href="https://catfact.ninja">cat facts</a> api to use it on registration page. Maybe it is not that necessary but it is always good to know some facts about cats :)

**Comment by 4teko7** [comment] 2021-06-08 21:58
I have found a Person api from randomuser.me. By this, we are creating a Person and doing some stuff related to People.

**Comment by emrahdgn** [comment] 2021-06-09 07:07
I will also use the [news api](https://newsapi.org/). It will provide a good opportunity for us to take some time off from the lectures these days and read the news about what's going on in the world.

**Comment by cemkaya-mpi** [comment] 2021-06-11 09:01
I used the google custom image search API. We can close this issue, since the assignment was submitted yesterday.

**Comment by gktpmuhammed** [comment] 2021-06-11 12:57
I used giphy API for showing some gifs. With this I can send some massages for our users.

**Comment by MrLebowski42** [comment] 2021-06-11 18:01
It is a bit late to mention but I used Youtube Data API and Youtube IFrame API to send queries on Youtube videos and to create players for those videos later on.

**Comment by MrLebowski42** [comment] 2021-06-13 16:06
I think we are also done with this part as we are past implementation stage. I'm closing this issue.

**Closed by MrLebowski42** 2021-06-13 16:06 UTC

**Comment by elxif** [comment] 2021-06-13 20:25
I forgot to add my part before the issue is closed. I found a simple API called Country, where we can grab the users' countries through their IP addresses. I used this tool.
